# Generated by Django 3.2 on 2021-10-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dentist', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient2dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Tish holatlari')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name="Xabar jo'natilgan vaqt")),
                ('is_read', models.BooleanField(verbose_name="O'qilganmi?")),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_recipient', to='dentist.user', verbose_name='Tish shifokori')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_sender', to='patient.user', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'P2D Xabar',
                'verbose_name_plural': 'P2D Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='Dentist2patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Tish holatlari')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name="Xabar jo'natilgan vaqt")),
                ('is_read', models.BooleanField(verbose_name="O'qilganmi?")),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_recipient', to='patient.user', verbose_name='Bemor')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_sender', to='dentist.user', verbose_name='Tish shifokori')),
            ],
            options={
                'verbose_name': 'D2P Xabar',
                'verbose_name_plural': 'D2P Xabarlar',
            },
        ),
    ]
