# Generated by Django 3.2 on 2021-10-22 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_illness_other_illness'),
        ('dentist', '0004_rename_specialty_user_speciality'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_dentist', to='dentist.user', verbose_name='Tish shifokori'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_patient', to='patient.user', verbose_name='Bemor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_service', to='dentist.service', verbose_name='Xizmat'),
        ),
        migrations.AlterField(
            model_name='query',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_dentist', to='dentist.user', verbose_name='Tish shifokori'),
        ),
        migrations.AlterField(
            model_name='query',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_patient', to='patient.user', verbose_name='Bemor'),
        ),
    ]
