# Generated by Django 3.2.7 on 2021-10-03 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('adress', models.CharField(max_length=100, null=True)),
                ('orientir', models.CharField(max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.language')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('adress', models.CharField(max_length=100, null=True)),
                ('birthday', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('specialty', models.CharField(max_length=30, null=True)),
                ('experience', models.CharField(max_length=30, null=True)),
                ('worktime_begin', models.TimeField()),
                ('worktime_end', models.TimeField()),
                ('is_fullday', models.BooleanField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.clinic')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.language')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(default=0)),
                ('duration', models.IntegerField()),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.user')),
            ],
        ),
        migrations.CreateModel(
            name='cabinet_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.user')),
            ],
        ),
    ]
