# Generated by Django 3.2 on 2021-10-14 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('orientir', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mo'ljal")),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_language', to='baseapp.language', verbose_name='Til')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_region', to='baseapp.region', verbose_name='Hudud')),
            ],
            options={
                'verbose_name': 'Shifoxona',
                'verbose_name_plural': 'Shifoxonalar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Telefon raqami')),
                ('birthday', models.DateField(verbose_name="Tug'ilgan sanasi")),
                ('image', models.ImageField(upload_to='dentists/photos/', verbose_name='Rasmi')),
                ('specialty', models.CharField(max_length=500, verbose_name='Soha')),
                ('experience', models.IntegerField(verbose_name='Tajriba')),
                ('worktime_begin', models.TimeField(verbose_name='Ish vaqti boshlanishi')),
                ('worktime_end', models.TimeField(verbose_name='Ish vaqti tugashi')),
                ('is_fullday', models.BooleanField(verbose_name='24 soat rejimi')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_clinic', to='dentist.clinic', verbose_name='Shifoxona')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_gender', to='baseapp.gender', verbose_name='Jins')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_gender', to='baseapp.language', verbose_name='Tili')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_user', to=settings.AUTH_USER_MODEL, verbose_name='Tish shifokori')),
            ],
            options={
                'verbose_name': 'Tish shifokori',
                'verbose_name_plural': 'Tish shifokorlari',
            },
        ),
    ]
