# Generated by Django 3.2 on 2021-10-18 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_user', to=settings.AUTH_USER_MODEL, verbose_name='Tish shifokori'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='FISh')),
                ('duration', models.TimeField(verbose_name='Xizmat davomiyligi')),
                ('price', models.IntegerField(verbose_name='Xizmat narxi')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.user', verbose_name='Tish shifokori')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='Cabinet_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dentists/cabinet_photos/', verbose_name='Rasm')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.user', verbose_name='Tish shifokori')),
            ],
            options={
                'verbose_name': 'Kabinet rasmi',
                'verbose_name_plural': 'Kabinet rasmlari',
            },
        ),
    ]
