# Generated by Django 3.2 on 2021-10-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0002_auto_20211018_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.CharField(default='1', max_length=255, verbose_name='Slug'),
        ),
    ]
