# Generated by Django 3.2 on 2021-10-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0003_user_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
