# Generated by Django 3.2 on 2021-10-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0001_initial'),
        ('dentist', '0004_rename_specialty_user_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Xizmat nomi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_language', to='baseapp.language', verbose_name='Tili'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_user', to=settings.AUTH_USER_MODEL, verbose_name='Tish shifokori'),
        ),
        migrations.CreateModel(
            name='User_translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='MyDentist dagi FIShi')),
                ('speciality', models.CharField(max_length=500, verbose_name='Soha')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_user_translation', to='dentist.user', verbose_name='Tish shifokori')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_language_translation', to='baseapp.language', verbose_name='Tili')),
            ],
            options={
                'verbose_name': "Tish shifokorining ma'lumoti",
                'verbose_name_plural': "Tish shifokorining ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='Service_translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Xizmat nomi')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_language_translation', to='baseapp.language', verbose_name='Tili')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_service_translation', to='dentist.service', verbose_name='Xizmat')),
            ],
            options={
                'verbose_name': "Xizmatning ma'lumoti",
                'verbose_name_plural': "Xizmatning ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='Clinic_translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('orientir', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mo'ljal")),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_clinic_translation', to='dentist.clinic', verbose_name='Shifoxona')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_language', to='baseapp.language', verbose_name='Til')),
            ],
            options={
                'verbose_name': "Shifoxonaning ma'lumoti",
                'verbose_name_plural': "Shifoxonaning ma'lumotlari",
            },
        ),
    ]
