# Generated by Django 3.2 on 2021-10-14 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tooth_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Holat nomi')),
                ('prefix', models.CharField(max_length=50, verbose_name="Holat qo'shimchasi")),
            ],
            options={
                'verbose_name': 'Tish holati',
                'verbose_name_plural': 'Tish holatlari',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('birthday', models.DateField(verbose_name="Tug'ilgan sanasi")),
                ('image', models.ImageField(upload_to='patients/photos/', verbose_name='Rasmi')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_gender', to='baseapp.gender', verbose_name='Jins')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_language', to='baseapp.language', verbose_name='Tili')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to=settings.AUTH_USER_MODEL, verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
            },
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Tish raqami')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tooth', to='patient.user', verbose_name='Bemor')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_tooth_status', to='patient.tooth_status', verbose_name='Tish holati')),
            ],
            options={
                'verbose_name': 'Tish',
                'verbose_name_plural': 'Tishlar',
            },
        ),
        migrations.CreateModel(
            name='Process_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='patients/process_photos/', verbose_name='Ish jarayonidagi rasm')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_process_photo', to='patient.user', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Tish holati',
                'verbose_name_plural': 'Tish holatlari',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ish nomi')),
                ('is_done', models.BooleanField(verbose_name='Qilinganligi')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_plan', to='patient.user', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Qilingan ish',
                'verbose_name_plural': 'Qilingan ishlar',
            },
        ),
    ]
