# Generated by Django 3.2 on 2021-10-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('illness', '0004_alcohol_blood_disease_epilepsy_heart_attack_medications_oncologic_pregnancy_stroke_tuberculosis'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.alcohol', verbose_name='Spirtli ichimlik ichasizmi?')),
                ('blood_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.blood_disease', verbose_name='Qon kasali')),
                ('epilepsy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.epilepsy', verbose_name='Epilepsiya')),
                ('heart_attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.heart_attack', verbose_name='Yurak xurujiga uchraganmisiz?')),
                ('medications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.medications', verbose_name='Doimiy dorilar')),
                ('oncologic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.oncologic', verbose_name='Onkologik kasalliklar')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.pregnancy', verbose_name='Homiladorlik')),
                ('stroke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.stroke', verbose_name='Insultga uchraganmisiz?')),
                ('tuberculosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.tuberculosis', verbose_name='Sil kasalligi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.user', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Bemor kasalligi',
                'verbose_name_plural': 'Bemor kasalliklari',
            },
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.aids', verbose_name='OITS')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.allergy', verbose_name='Allergiya')),
                ('anesthesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.anesthesia', verbose_name='Narkoz')),
                ('asthma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.asthma', verbose_name='Bronxial astma')),
                ('diabet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.diabet', verbose_name='Qandli diabet')),
                ('dizziness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.dizziness', verbose_name='Bosh aylanishi')),
                ('hepatitis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.hepatitis', verbose_name='Gepatit B')),
                ('pressure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.pressure', verbose_name='Qon bosimi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.user', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Bemor kasalligi',
                'verbose_name_plural': 'Bemor kasalliklari',
            },
        ),
    ]
